spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

cloud.aws.region=ap-northeast-2
cloud.aws.s3.bucket=balltalk-images-lucan
cloud.aws.cloudfront.domain=https://d1ig7i2osln48n.cloudfront.net

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB